Analytics docs
kubefirst/kubefirst pull request #1254
Opened 2023-02-01 20:57 UTC by robertkeithrippetoe

Also update for local destroy doc

2023-02-07 17:05 UTC, jarededwards submitted a review, later dismissed

2023-02-08 21:37 UTC, fharper commented
@robertkeithrippetoe: sorry for the delay, but can you fix the conflicts please? I'll review this PR after :)

2023-02-23 18:00 UTC, fharper commented
sorry for the delay @robertkeithrippetoe , I completely forgot about this PR. I added some comments or modifications requests. I also push some commits, please validate that they are fine with you also.

2023-02-23 19:14 UTC, fharper requested changes

2023-02-23 20:58 UTC, robertkeithrippetoe commented on docs/explore/open-telemetry.md
> +### KubeFirst Allows You to Opt out of Data Collection
Added under mkdocs

2023-02-23 20:58 UTC, robertkeithrippetoe commented on docs/explore/open-telemetry.md
> +Kubefirst collects data around users in order to optimize future releases. By collecting metrics on what type of clusters are being deployed and how they are being used, Kubefirst prioritizes the fea
Added collected metrics

2023-02-23 20:58 UTC, robertkeithrippetoe commented on docs/kubefirst/local/destroy.md
> +Manual Destroy CLI Example:
Moved to FAQ

2023-02-23 21:08 UTC, fharper approved these changes
LGTM, good job @robertkeithrippetoe

2023-02-23 21:08 UTC, merged