first draft of the contributing guide
kubefirst/kubefirst pull request #931
Opened 2022-12-15 16:51 UTC by fharper

Signed-off-by: Frédéric Harper <hi@fred.dev>

2022-12-15 16:58 UTC, pagottoo submitted a review, later dismissed

2022-12-15 16:59 UTC, fharper commented
Please do not merge yet, @converge will check what is the issue with [Test CI failing](https://github.com/kubefirst/kubefirst/issues/903) since it failed with this PR.

2022-12-15 17:28 UTC, johndietz requested changes

2022-12-15 17:28 UTC, johndietz commented on CONTRIBUTING.md
> +b
```suggestion

```

2022-12-15 17:28 UTC, johndietz commented on CONTRIBUTING.md
> +Firstly, we want to thank you for investing your precious time to contribute to Kubefirst!
```suggestion
Firstly, we want to thank you for investing your valuable time to contribute to Kubefirst!
```
precious comes across as sarcastic to my ear

2022-12-15 17:28 UTC, johndietz commented on CONTRIBUTING.md
> +At Kubefirst, we believe that every contribution are valuable, not just the code one, which means we welcome
```suggestion
At Kubefirst, we believe that every contribution is valuable, not just the code one, which means we welcome
```

2022-12-15 17:28 UTC, johndietz commented on CONTRIBUTING.md
> +If you need help in your Kubefirst journey as a contributor, please join our [Slack Community](http://kubefirst.io/slack). We have the `#kubefirst-oss` channel where you can ask any questions or get
```suggestion
If you need help in your Kubefirst journey as a contributor, please join our [Slack Community](http://kubefirst.io/slack). We have the `#kubefirst-oss` channel where you can ask any questions or get help with anything contribution-related. For support as a user, please ask in the `#helping-hands` channel, or directly to @fharper (Fred in Slack), our Developer Advocate.
```

2022-12-15 17:29 UTC, converge commented
tks for the heads up @fharper ! We actually just broke the unit test, Im checking with the team if anyone can fix it.

2022-12-16 14:51 UTC, converge commented
> @converge : so can I merge this PR or you need it to test it?

sorry for the delay, we can merge.

2022-12-16 14:52 UTC, converge approved these changes

2022-12-16 19:09 UTC, pagottoo approved these changes

2022-12-16 19:18 UTC, merged